# Generated by Django 2.2.5 on 2019-11-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
