# Generated by Django 2.2.5 on 2019-11-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0002_reg_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
    ]
