# Generated by Django 2.2.5 on 2019-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0007_add_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='fed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('feed', models.TextField(null=True)),
            ],
        ),
    ]
