# Generated by Django 2.2.5 on 2019-12-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0009_auto_20191231_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='img',
            new_name='cover_img',
        ),
    ]
