# Generated by Django 2.2.5 on 2020-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0011_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='fedre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('feedreplay', models.TextField(null=True)),
            ],
        ),
    ]
