# Generated by Django 2.2.5 on 2020-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0012_fedre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedre',
            name='date',
            field=models.CharField(default=-2020, max_length=100),
            preserve_default=False,
        ),
    ]
