# Generated by Django 2.2.5 on 2020-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0013_fedre_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fed',
            name='date',
            field=models.CharField(default=-2020, max_length=100),
            preserve_default=False,
        ),
    ]
