# Generated by Django 2.2.5 on 2020-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0014_fed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fed',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fedre',
            name='date',
            field=models.DateField(),
        ),
    ]
