# Generated by Django 2.2.5 on 2020-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0015_auto_20200104_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedre',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
