# Generated by Django 2.2.5 on 2020-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0017_auto_20200104_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedre',
            name='date',
            field=models.DateField(),
        ),
    ]
