# Generated by Django 2.2.5 on 2020-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0019_auto_20200104_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fed',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
