# Generated by Django 2.2.5 on 2020-01-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationfinder', '0021_auto_20200104_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='locre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('userid', models.CharField(max_length=100)),
                ('locstatus', models.TextField(null=True)),
            ],
        ),
    ]
